### ISSUE TITLE
The README File is not supporting WebP anymore

### ISSUE THREAD

**Issue by SkySung** [TomasHubelbauer/markdown-webp#4]
Sad news, I don't know why, but the GitHub team seems to have stopped supporting WebP. The following picture is the edited paragraph, and it prevents me from uploading WebP files.

<img width="1426" alt="截圖 2024-08-02 下午4 23 13" src="https://github.com/user-attachments/assets/2c1c4cd1-d8bf-406c-8148-b8038138209c">

**Comment by TomasHubelbauer** [comment]
What browser are you using?

**Comment by SkySung** [comment]
Hi! I've updated the description, you're too fast for me to keep up with haha.

**Comment by TomasHubelbauer** [comment]
Oh that's unfortunate. I still see the WebP in the readme in this repo, so it looks like there is still support for serving it and letting the browser render it. So I think you can work around by editing locally and committing the WebP you want to add locally as well.

**Comment by SkySung** [comment]
Yes, you're right, I've tried embedding WebP locally and pushed it. It works fine!
Thank you for the informative discussion!

**Comment by TomasHubelbauer** [comment]
The pleasure is mine! Have a good one 😌
